version: '3.8'
services:
  www:
    build:
      context: .
      args:
        - dir=ejemplo
        - DB_HOST=mysql_example
    ports:
      - 8080:80
    networks:
      - prueba 
    depends_on:
      - db 

  db:
    image: mariadb
    container_name: mysql_example 
    volumes:
      - container-volume:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MARIADB_ROOT_PASSWORD: secret 
      MARIADB_USER: sampleuser 
      MARIADB_PASSWORD: samplepass
      MARIADB_DATABASE: sample
    ports:
      - "3306:3306"
    networks:
      - prueba

volumes:
  container-volume:

networks:
   prueba:
     driver: bridge
